### ISSUE TITLE
README - Usage - const name

### ISSUE THREAD

**Issue by mcr85** [spencerstark/PreloadCSSWebpackPlugin#1]
Thank you for this plugin.
You may want to unify naming in *Usage* section of README file:

You have:
`const PreloadCSSPlugin = require("preload-css-webpack-plugin");`

then:
`new PreloadCssPlugin()`

**Comment by spnc-omz** [comment]
@mcr85 I've updated the readme, can you please confirm it looks good? Thanks!

**Comment by mcr85** [comment]
It's ok now. No more problems with brainless code copying ;)

**Comment by spnc-omz** [comment]
Thanks @mcr85 !
