### ISSUE TITLE
Is there any way to provide onError handler to link?

### ISSUE THREAD

**Issue by mborseparagyte** [spencerstark/PreloadCSSWebpackPlugin#2]

**Comment by spnc-omz** [comment]
@mborseparagyte not currently, no. Can you help me understand the use case for this? I can look at building dynamic variability into the link script. Currently it's hard coded for only this.onload, but I don't see why we couldn't make it more variable.

**Comment by mborseparagyte** [comment]
Sometimes browser versions are not compatible with preload services, in that case, we need to handle onError too.
You can take Mozilla firefox V. 56 as an example.

**Comment by spnc-omz** [comment]
I think that https://github.com/spnc-omz/PreloadCSSWebpackPlugin/pull/3 should address your wants. If it does, I'll merge it and publish. 

Let me know what you think @mborseparagyte :)

**Comment by mborseparagyte** [comment]
Exactly what I wanted! plz merge it asap. Thanks, @spnc-omz.

**Comment by spnc-omz** [comment]
@mborseparagyte  Have at it. 0.2.0 is available on NPM. Sorry for the delay in getting a resolution!
